baseURL = 'https://manrique.dev/'
languageCode = 'es-es'
title = 'Manrique.dev'
theme = 'PaperMod'

DefaultContentLanguage = "es"
googleAnalytics = "G-LZ04D7545K"
enableRobotsTXT = true



[caches]
  [caches.images]
    dir = ':cacheDir/images'
